
-- Enable necessary extensions if needed
-- create extension if not exists "uuid-ossp";

-- Categorias
create table if not exists categorias (
  id bigint generated by default as identity primary key,
  nombre text not null,
  slug text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Productos
create table if not exists productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  precio numeric not null,
  stock integer not null default 0,
  imagen_url text,
  imagenes text[],
  categoria_id bigint references categorias(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Clientes
create table if not exists clientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  telefono text,
  direccion text,
  es_problematico boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Pedidos
create table if not exists pedidos (
  id bigint generated by default as identity primary key,
  cliente_id bigint references clientes(id) on delete set null,
  total numeric not null,
  status text check (status in ('Pendiente', 'Confirmado', 'Preparando', 'Enviado', 'Entregado', 'Fallido', 'Devuelto')) default 'Pendiente',
  pago_status text check (pago_status in ('Pendiente', 'Pagado Anticipado', 'Pago Contraentrega', 'Pagado al Recibir')) default 'Pendiente',
  voucher_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Pedido Items
create table if not exists pedido_items (
  id bigint generated by default as identity primary key,
  pedido_id bigint references pedidos(id) on delete cascade,
  producto_id bigint references productos(id) on delete set null,
  cantidad integer not null
);

-- Incidencias
create table if not exists incidencias (
  id bigint generated by default as identity primary key,
  pedido_id bigint references pedidos(id) on delete cascade,
  tipo text,
  comentario text,
  foto text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists cupones (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  tipo text not null default 'porcentaje' check (tipo in ('porcentaje', 'monto')),
  valor numeric not null,
  activo boolean not null default true,
  min_total numeric not null default 0,
  max_usos integer,
  usos integer not null default 0,
  starts_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table pedidos add column if not exists subtotal numeric;
alter table pedidos add column if not exists descuento numeric default 0;
alter table pedidos add column if not exists cupon_codigo text;
