-- =====================================================================
-- 🛡️ Tienda Blama 2026 - Esquema Maestro de Base de Datos (Producción Consolidado)
-- =====================================================================
-- Este archivo contiene la definición completa, fiel y consolidada del estado
-- original de la base de datos de producción (PROD).
-- Incluye la definición de tablas, vistas, funciones (RPC), disparadores (triggers),
-- políticas de seguridad RLS y cubos de almacenamiento.
-- =====================================================================

-- Habilitar extensiones necesarias
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==========================================
-- 📂 1. Definición de Tablas del Negocio
-- ==========================================

-- Categorías (Jerarquía de Catálogo)
CREATE TABLE IF NOT EXISTS public.categorias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    slug text NOT NULL UNIQUE,
    parent_id bigint REFERENCES public.categorias(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Catálogo de Productos
CREATE TABLE IF NOT EXISTS public.productos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    precio numeric NOT NULL,
    precio_antes numeric,
    stock integer DEFAULT 0 NOT NULL,
    imagen_url text,
    imagenes text[],
    videos text[],
    categoria_id bigint REFERENCES public.categorias(id) ON DELETE SET NULL,
    descripcion text,
    materiales text,
    tamano text,
    color text,
    cuidados text,
    uso text,
    calificacion numeric DEFAULT 5.0,
    fts tsvector GENERATED ALWAYS AS (
        ((setweight(to_tsvector('spanish'::regconfig, COALESCE(nombre, ''::text)), 'A'::"char") || 
          setweight(to_tsvector('spanish'::regconfig, COALESCE(descripcion, ''::text)), 'B'::"char")) || 
          setweight(to_tsvector('spanish'::regconfig, COALESCE(materiales, ''::text)), 'C'::"char"))
    ) STORED,
    slug text UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Clientes (CRM)
CREATE TABLE IF NOT EXISTS public.clientes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    telefono text,
    dni text,
    email text,
    direccion text,
    departamento text,
    provincia text,
    distrito text,
    referencia text,
    link_ubicacion text,
    es_problematico boolean DEFAULT false,
    updated_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Pedidos (Checkout / Operaciones)
CREATE TABLE IF NOT EXISTS public.pedidos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id bigint REFERENCES public.clientes(id) ON DELETE SET NULL,
    total numeric NOT NULL,
    subtotal numeric,
    descuento numeric DEFAULT 0,
    cupon_codigo text,
    status text DEFAULT 'Pendiente'::text CHECK (status = ANY (ARRAY['Pendiente'::text, 'Confirmado'::text, 'Preparando'::text, 'Enviado'::text, 'Llegó a Agencia'::text, 'Entregado'::text, 'Fallido'::text, 'Devuelto'::text, 'Cancelado'::text])),
    pago_status text DEFAULT 'Pendiente'::text CHECK (pago_status = ANY (ARRAY['Pendiente'::text, 'Pago Parcial'::text, 'Pagado'::text, 'Pago Contraentrega'::text, 'Pagado Anticipado'::text, 'Pagado al Recibir'::text, 'Fallido'::text])),
    stock_descontado boolean DEFAULT false NOT NULL,
    metodo_envio text,
    voucher_url text,
    guia_archivo_url text,
    comprobante_pago_url text[],
    evidencia_entrega_url text,
    nombre_contacto text,
    dni_contacto text,
    telefono_contacto text,
    email_contacto text,
    departamento text,
    provincia text,
    distrito text,
    direccion_calle text,
    referencia_direccion text,
    link_ubicacion text,
    codigo_seguimiento text,
    shalom_orden text,
    shalom_clave text,
    shalom_pin text,
    agencia_origen text,
    agencia_destino text,
    culqi_charge_id text,
    email_confirmacion_enviado boolean DEFAULT false,
    asignado_a uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    fecha_asignacion timestamp with time zone,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

COMMENT ON COLUMN public.pedidos.agencia_origen IS 'Agencia de despacho (ej: Shalom La Victoria)';
COMMENT ON COLUMN public.pedidos.agencia_destino IS 'Agencia de destino o dirección (ej: Shalom Trujillo Centro)';
COMMENT ON COLUMN public.pedidos.culqi_charge_id IS 'ID del cargo en Culqi (chr_live_...). Se guarda al confirmarse el pago con tarjeta para validar la URL de éxito del cliente.';
COMMENT ON COLUMN public.pedidos.email_confirmacion_enviado IS 'Indica si se ha enviado el correo electrónico de confirmación de compra al cliente.';

-- Pedido Items
CREATE TABLE IF NOT EXISTS public.pedido_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint REFERENCES public.pedidos(id) ON DELETE CASCADE,
    producto_id bigint REFERENCES public.productos(id) ON DELETE SET NULL,
    producto_variante_id bigint, -- Se definirá la foreign key después de crear la tabla
    cantidad integer NOT NULL,
    precio_unitario numeric,
    producto_nombre text,
    variante_nombre text,
    cantidad_devuelta integer DEFAULT 0
);

-- Incidencias (Atención al Cliente)
CREATE TABLE IF NOT EXISTS public.incidencias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint REFERENCES public.pedidos(id) ON DELETE CASCADE,
    tipo text,
    comentario text,
    foto text,
    fotos text[],
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Cupones de Descuento
CREATE TABLE IF NOT EXISTS public.cupones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo text NOT NULL UNIQUE,
    tipo text DEFAULT 'porcentaje'::text CHECK (tipo = ANY (ARRAY['porcentaje'::text, 'monto'::text])),
    valor numeric NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    min_total numeric DEFAULT 0 NOT NULL,
    max_usos integer,
    usos integer DEFAULT 0 NOT NULL,
    starts_at timestamp with time zone,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Variantes del Producto (Tallas / Colores)
CREATE TABLE IF NOT EXISTS public.producto_variantes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id bigint REFERENCES public.productos(id) ON DELETE CASCADE NOT NULL,
    etiqueta text NOT NULL,
    talla text,
    color text,
    modelo text,
    precio numeric,
    precio_antes numeric,
    stock integer DEFAULT 0 NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Agregar la foreign key faltante en pedido_items
ALTER TABLE public.pedido_items 
ADD CONSTRAINT pedido_items_producto_variante_id_fkey 
FOREIGN KEY (producto_variante_id) REFERENCES public.producto_variantes(id) ON DELETE SET NULL;

-- Especificaciones de Ficha Técnica
CREATE TABLE IF NOT EXISTS public.producto_especificaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id bigint REFERENCES public.productos(id) ON DELETE CASCADE NOT NULL,
    clave text NOT NULL,
    valor text,
    orden integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Home Banners (Carrusel Principal)
CREATE TABLE IF NOT EXISTS public.home_banners (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text,
    subtitle text,
    cta text,
    href text NOT NULL,
    orden integer DEFAULT 0 NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    countdown_end timestamp with time zone,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Reseñas de Productos (Fidelización)
CREATE TABLE IF NOT EXISTS public.product_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint REFERENCES public.productos(id) ON DELETE CASCADE NOT NULL,
    order_id bigint REFERENCES public.pedidos(id) ON DELETE SET NULL,
    rating integer CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    title text,
    body text NOT NULL,
    customer_name text,
    customer_city text,
    photo_urls text[],
    verified boolean DEFAULT false NOT NULL,
    approved boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Preguntas de Clientes
CREATE TABLE IF NOT EXISTS public.product_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint REFERENCES public.productos(id) ON DELETE CASCADE NOT NULL,
    question text NOT NULL,
    asker_name text,
    asker_phone text,
    published boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Respuestas del Administrador
CREATE TABLE IF NOT EXISTS public.product_answers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id bigint REFERENCES public.product_questions(id) ON DELETE CASCADE NOT NULL,
    answer text NOT NULL,
    answered_by text,
    published boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Announcement Bar (Barra Superior Notificaciones)
CREATE TABLE IF NOT EXISTS public.announcement_bar (
    id bigint PRIMARY KEY,
    enabled boolean DEFAULT true NOT NULL,
    interval_ms integer DEFAULT 3500 NOT NULL,
    messages text[] DEFAULT '{}'::text[] NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Redes Sociales y Contactos
CREATE TABLE IF NOT EXISTS public.social_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform text NOT NULL,
    url text NOT NULL,
    active boolean DEFAULT true,
    orden integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Perfiles de Staff y Usuarios (CRM)
CREATE TABLE IF NOT EXISTS public.usuarios (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email text,
    nombre text,
    role text DEFAULT 'user'::text,
    telefono text,
    activo boolean DEFAULT true,
    intentos_fallidos integer DEFAULT 0,
    bloqueado_hasta timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

-- Logs de Actividad de Pedidos
CREATE TABLE IF NOT EXISTS public.pedido_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint REFERENCES public.pedidos(id) ON DELETE CASCADE NOT NULL,
    usuario_nombre text,
    accion text NOT NULL,
    detalles text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Auditoría General de Base de Datos
CREATE TABLE IF NOT EXISTS public.system_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name text NOT NULL,
    record_id text NOT NULL,
    action text NOT NULL,
    old_data jsonb,
    new_data jsonb,
    changed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    changed_at timestamp with time zone DEFAULT now()
);

-- Finanzas: Registros de Pagos
CREATE TABLE IF NOT EXISTS public.pedido_pagos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint REFERENCES public.pedidos(id) ON DELETE CASCADE NOT NULL,
    monto numeric CHECK (monto > 0::numeric) NOT NULL,
    metodo_pago text CHECK (metodo_pago = ANY (ARRAY['Efectivo'::text, 'Yape'::text, 'Plin'::text, 'Transferencia BCP'::text, 'Transferencia Interbank'::text, 'Tarjeta'::text, 'Pasarela Culqi'::text, 'Otro'::text])) NOT NULL,
    tipo_pago text CHECK (tipo_pago = ANY (ARRAY['Adelanto'::text, 'Abono'::text, 'Pago Final'::text, 'Reembolso'::text])) NOT NULL,
    comprobante_url text,
    nota text,
    registrado_por text DEFAULT 'Sistema'::text NOT NULL,
    registrado_por_id uuid REFERENCES public.usuarios(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- CRM: Notas del Administrador
CREATE TABLE IF NOT EXISTS public.pedido_notas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint REFERENCES public.pedidos(id) ON DELETE CASCADE NOT NULL,
    autor_id uuid REFERENCES public.usuarios(id) ON DELETE SET NULL,
    autor_nombre text NOT NULL,
    contenido text NOT NULL,
    tipo text DEFAULT 'info'::text CHECK (tipo = ANY (ARRAY['info'::text, 'alerta'::text, 'urgente'::text])),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Libro de Reclamaciones Oficial (INDECOPI)
CREATE SEQUENCE IF NOT EXISTS public.libro_reclamaciones_seq;
CREATE TABLE IF NOT EXISTS public.libro_reclamaciones (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    codigo text UNIQUE DEFAULT ((('LR-'::text || to_char(now(), 'YYYY'::text)) || '-'::text) || lpad((nextval('libro_reclamaciones_seq'::regclass))::text, 6, '0'::text)),
    nombres text NOT NULL,
    apellidos text NOT NULL,
    tipo_documento text DEFAULT 'DNI'::text,
    numero_documento text NOT NULL,
    email text NOT NULL,
    telefono text NOT NULL,
    direccion text NOT NULL,
    departamento text,
    provincia text,
    distrito text,
    menor_edad boolean DEFAULT false,
    apoderado_nombres text,
    apoderado_dni text,
    tipo_bien text CHECK (tipo_bien = ANY (ARRAY['PRODUCTO'::text, 'SERVICIO'::text])) NOT NULL,
    monto_reclamado numeric,
    descripcion_bien text,
    tipo_reclamo text CHECK (tipo_reclamo = ANY (ARRAY['QUEJA'::text, 'RECLAMO'::text])) NOT NULL,
    detalle_reclamo text NOT NULL,
    pedido_relacionado text,
    archivo_adjunto text,
    estado text DEFAULT 'PENDIENTE'::text CHECK (estado = ANY (ARRAY['PENDIENTE'::text, 'EN_PROCESO'::text, 'CERRADO'::text])),
    observaciones_proveedor text,
    fecha_respuesta timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

-- Almacenes
CREATE TABLE IF NOT EXISTS public.almacenes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    direccion text,
    activo boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Kardex contable de movimientos
CREATE TABLE IF NOT EXISTS public.inventario_movimientos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id bigint REFERENCES public.productos(id) ON DELETE CASCADE NOT NULL,
    variante_id bigint REFERENCES public.producto_variantes(id) ON DELETE SET NULL,
    almacen_id bigint REFERENCES public.almacenes(id) ON DELETE SET NULL DEFAULT 1,
    tipo_movimiento text CHECK (tipo_movimiento = ANY (ARRAY['ENTRADA_COMPRA'::text, 'SALIDA_VENTA'::text, 'AJUSTE'::text, 'DEVOLUCION'::text, 'TRASLADO'::text, 'AJUSTE_INICIAL'::text])),
    cantidad integer NOT NULL,
    costo_unitario numeric DEFAULT 0.00 NOT NULL,
    referencia text,
    notas text,
    created_by uuid REFERENCES public.usuarios(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Píxeles de Marketing (GTM, Facebook, TikTok)
CREATE TABLE IF NOT EXISTS public.marketing_pixels (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar NOT NULL,
    clave varchar NOT NULL UNIQUE,
    pixel_id varchar DEFAULT '',
    enabled boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Suscripciones de Newsletter
CREATE TABLE IF NOT EXISTS public.newsletter_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    cupon_codigo text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 📂 2. Índices de Rendimiento
-- ==========================================
CREATE INDEX IF NOT EXISTS producto_variantes_producto_id_idx ON public.producto_variantes (producto_id);
CREATE INDEX IF NOT EXISTS producto_especificaciones_producto_id_idx ON public.producto_especificaciones (producto_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_cliente_id ON public.pedidos (cliente_id);
CREATE INDEX IF NOT EXISTS idx_pedido_items_pedido_id ON public.pedido_items (pedido_id);
CREATE INDEX IF NOT EXISTS idx_pedido_items_producto_id ON public.pedido_items (producto_id);
CREATE INDEX IF NOT EXISTS idx_inventario_movimientos_producto_variante ON public.inventario_movimientos (producto_id, variante_id);

-- ==========================================
-- 📂 3. Vistas Contables
-- ==========================================

-- Kardex Valorizado View
CREATE OR REPLACE VIEW public.kardex_valorizado_view AS
 SELECT m.id,
    m.producto_id,
    p.nombre AS producto_nombre,
    m.variante_id,
    pv.etiqueta AS variante_nombre,
    m.almacen_id,
    a.nombre AS almacen_nombre,
    m.tipo_movimiento,
    m.referencia,
    m.notas,
    m.costo_unitario,
    m.cantidad,
        CASE
            WHEN (m.cantidad > 0) THEN m.cantidad
            ELSE 0
        END AS entradas,
        CASE
            WHEN (m.cantidad < 0) THEN abs(m.cantidad)
            ELSE 0
        END AS salidas,
    ((m.cantidad)::numeric * m.costo_unitario) AS valor_total,
    sum(m.cantidad) OVER (PARTITION BY m.producto_id, m.variante_id, m.almacen_id ORDER BY m.created_at, m.id) AS saldo_cantidad,
    m.created_at,
    m.created_by,
    u.nombre AS usuario_nombre,
    u.email AS usuario_email
   FROM ((((public.inventario_movimientos m
     LEFT JOIN public.productos p ON ((m.producto_id = p.id)))
     LEFT JOIN public.producto_variantes pv ON ((m.variante_id = pv.id)))
     LEFT JOIN public.almacenes a ON ((m.almacen_id = a.id)))
     LEFT JOIN public.usuarios u ON ((m.created_by = u.id)));

-- ==========================================
-- 📂 4. Funciones PL/pgSQL y RPCs
-- ==========================================

-- Buscar nombre por Email
CREATE OR REPLACE FUNCTION public.get_user_name_by_email(p_email text)
RETURNS text AS $$
DECLARE
    v_nombre text;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Comprobar si usuario es Superadmin/Admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN (SELECT role FROM public.usuarios WHERE id = auth.uid()) IN ('admin', 'superadmin');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Comprobar si usuario es Staff (Admin, Superadmin, Worker)
CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.usuarios u
    WHERE u.id = auth.uid()
      AND u.role IN ('admin', 'superadmin', 'worker')
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Comprobar acceso a Pedido
CREATE OR REPLACE FUNCTION public.can_access_pedido(pedido_id bigint)
RETURNS boolean AS $$
BEGIN
  RETURN public.is_admin()
    OR EXISTS (
      SELECT 1
      FROM public.pedidos p
      WHERE p.id = pedido_id
        AND p.asignado_a = auth.uid()
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Slugify utility
CREATE OR REPLACE FUNCTION public.slugify(value text)
RETURNS text AS $$
BEGIN
  RETURN trim(both '-' from regexp_replace(lower(value), '[^a-z0-9]+', '-', 'g'));
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Trigger: Generar Slug de Producto
CREATE OR REPLACE FUNCTION public.handle_new_product_slug()
RETURNS trigger AS $$
DECLARE
  base_slug text;
  new_slug text;
BEGIN
  base_slug := public.slugify(NEW.nombre);
  new_slug := base_slug;
  IF EXISTS (SELECT 1 FROM public.productos WHERE slug = new_slug) THEN
     new_slug := base_slug || '-' || floor(random() * 10000)::text;
  END IF;
  NEW.slug := new_slug;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger: Registrar nuevos usuarios registrados por auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.usuarios (id, email, nombre, role, created_at)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', 'user', now())
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger: Aplicación de Cupones en Pedidos
CREATE OR REPLACE FUNCTION public.apply_coupon_to_pedido()
RETURNS trigger AS $$
DECLARE
  v_code text;
  v_descuento numeric;
  v_rows int;
  v_tipo text;
  v_valor numeric;
  v_activo boolean;
  v_min_total numeric;
  v_max_usos int;
  v_usos int;
  v_starts_at timestamptz;
  v_expires_at timestamptz;
BEGIN
  IF new.cupon_codigo IS NULL OR length(trim(new.cupon_codigo)) = 0 THEN
    RETURN new;
  END IF;

  IF new.subtotal IS NULL THEN
    RAISE EXCEPTION 'Subtotal requerido para aplicar cupón';
  END IF;

  v_code := upper(trim(new.cupon_codigo));

  SELECT c.tipo, c.valor, c.activo, c.min_total, c.max_usos, c.usos, c.starts_at, c.expires_at
    INTO v_tipo, v_valor, v_activo, v_min_total, v_max_usos, v_usos, v_starts_at, v_expires_at
  FROM public.cupones c
  WHERE c.codigo = v_code
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Cupón inválido';
  END IF;

  IF v_activo IS NOT TRUE THEN
    RAISE EXCEPTION 'Cupón inactivo';
  END IF;

  IF v_starts_at IS NOT NULL AND now() < v_starts_at THEN
    RAISE EXCEPTION 'Cupón aún no disponible';
  END IF;

  IF v_expires_at IS NOT NULL AND now() > v_expires_at THEN
    RAISE EXCEPTION 'Cupón expiró';
  END IF;

  IF coalesce(new.subtotal, 0) < coalesce(v_min_total, 0) THEN
    RAISE EXCEPTION 'El cupón no aplica para este total';
  END IF;

  IF v_max_usos IS NOT NULL AND v_usos >= v_max_usos THEN
    RAISE EXCEPTION 'Cupón agotado';
  END IF;

  IF v_tipo = 'porcentaje' THEN
    v_descuento := round(coalesce(new.subtotal, 0) * (coalesce(v_valor, 0) / 100.0), 2);
  ELSE
    v_descuento := coalesce(v_valor, 0);
  END IF;

  v_descuento := greatest(0, least(coalesce(new.subtotal, 0), v_descuento));

  UPDATE public.cupones
     SET usos = usos + 1
   WHERE codigo = v_code
     AND (max_usos IS NULL OR usos < max_usos);

  GET DIAGNOSTICS v_rows = row_count;
  IF v_rows = 0 THEN
    RAISE EXCEPTION 'Cupón agotado';
  END IF;

  new.cupon_codigo := v_code;
  new.descuento := v_descuento;
  new.total := greatest(0, round((coalesce(new.subtotal, 0) - v_descuento), 2));

  RETURN new;
END;
$$ LANGUAGE plpgsql;

-- Check User Role by Required Roles Array
CREATE OR REPLACE FUNCTION public.check_user_role(required_roles text[])
RETURNS boolean AS $$
DECLARE
  current_user_role text;
BEGIN
  SELECT role INTO current_user_role
  FROM public.usuarios
  WHERE id = auth.uid();
  
  IF current_user_role IS NULL THEN
    current_user_role := (current_setting('request.jwt.claims', true)::jsonb ->> 'user_metadata')::jsonb ->> 'role';
  END IF;
  
  IF current_user_role IS NULL THEN
    current_user_role := 'user';
  END IF;
  
  IF current_user_role = 'superadmin' AND 'admin' = ANY(required_roles) THEN
    RETURN true;
  END IF;

  RETURN current_user_role = ANY(required_roles);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Obtener Estadísticas del Panel Admin
CREATE OR REPLACE FUNCTION public.get_admin_dashboard_stats(p_user_id uuid)
RETURNS json AS $$
DECLARE
  v_result json;
BEGIN
  SELECT json_build_object(
    'totalVentasReales', COALESCE((SELECT SUM(total) FROM pedidos WHERE status = 'Entregado'), 0),
    'ventasHoy', COALESCE((SELECT SUM(total) FROM pedidos WHERE status = 'Entregado' AND created_at >= CURRENT_DATE), 0),
    'pedidosPendientes', (SELECT COUNT(*) FROM pedidos WHERE status = 'Pendiente'),
    'pedidosEnProceso', (SELECT COUNT(*) FROM pedidos WHERE status IN ('Confirmado', 'Enviado', 'Preparando')),
    'pedidosEntregados', (SELECT COUNT(*) FROM pedidos WHERE status = 'Entregado'),
    'pedidosAsignados', (SELECT COUNT(*) FROM pedidos WHERE asignado_a = p_user_id AND status NOT IN ('Fallido', 'Devuelto', 'Entregado')),
    'totalClientes', (SELECT COUNT(*) FROM clientes),
    'productosLowStock', (SELECT COUNT(*) FROM productos WHERE stock < 5)
  ) INTO v_result;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Devolución Parcial del Pedido
CREATE OR REPLACE FUNCTION public.admin_procesar_devolucion_parcial(
    p_item_id bigint, 
    p_cantidad_a_devolver integer, 
    p_usuario_nombre text, 
    p_pedido_id bigint
) RETURNS void AS $$
DECLARE
  v_producto_id bigint;
  v_cantidad_actual int;
  v_cantidad_ya_devuelta int;
  v_stock_descontado boolean;
BEGIN
  SELECT 
    pi.producto_id, 
    pi.cantidad, 
    pi.cantidad_devuelta,
    p.stock_descontado
  INTO 
    v_producto_id, 
    v_cantidad_actual, 
    v_cantidad_ya_devuelta,
    v_stock_descontado
  FROM pedido_items pi
  JOIN pedidos p ON p.id = pi.pedido_id
  WHERE pi.id = p_item_id;

  IF v_producto_id IS NULL THEN
    RAISE EXCEPTION 'El item no existe';
  END IF;

  IF (v_cantidad_ya_devuelta + p_cantidad_a_devolver) > v_cantidad_actual THEN
    RAISE EXCEPTION 'No puedes devolver más productos de los que se compraron';
  END IF;

  UPDATE pedido_items
  SET cantidad_devuelta = cantidad_devuelta + p_cantidad_a_devolver
  WHERE id = p_item_id;

  IF v_stock_descontado THEN
    -- Realizar un ingreso por devolución en Kardex para ajustar automáticamente el stock
    INSERT INTO public.inventario_movimientos (
        producto_id,
        almacen_id,
        tipo_movimiento,
        cantidad,
        costo_unitario,
        referencia,
        notas,
        created_at
    ) VALUES (
        v_producto_id,
        1,
        'DEVOLUCION',
        p_cantidad_a_devolver,
        public.get_costo_promedio(v_producto_id, null),
        'DEVOLUCION-PARCIAL-' || p_pedido_id::text,
        'Ingreso de stock por devolución parcial parcial',
        now()
    );
  END IF;

  INSERT INTO pedido_logs (pedido_id, usuario_nombre, accion, detalles)
  VALUES (
    p_pedido_id, 
    p_usuario_nombre, 
    'Devolución Parcial', 
    'Se devolvieron ' || p_cantidad_a_devolver || ' unidad(es) del producto ID ' || v_producto_id
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger: Logging en system_audit_logs
CREATE OR REPLACE FUNCTION public.log_changes_trigger()
RETURNS trigger AS $$
DECLARE
    sys_user UUID;
    record_identifier TEXT;
BEGIN
    sys_user := auth.uid();
    CASE TG_OP
        WHEN 'INSERT' THEN
            record_identifier := NEW.id::TEXT;
        WHEN 'UPDATE' THEN
            record_identifier := NEW.id::TEXT;
        WHEN 'DELETE' THEN
            record_identifier := OLD.id::TEXT;
    END CASE;

    IF TG_OP = 'INSERT' THEN
        INSERT INTO system_audit_logs (table_name, record_id, action, new_data, changed_by)
        VALUES (TG_TABLE_NAME, record_identifier, 'INSERT', row_to_json(NEW)::jsonb, sys_user);
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        IF NEW IS DISTINCT FROM OLD THEN
            INSERT INTO system_audit_logs (table_name, record_id, action, old_data, new_data, changed_by)
            VALUES (TG_TABLE_NAME, record_identifier, 'UPDATE', row_to_json(OLD)::jsonb, row_to_json(NEW)::jsonb, sys_user);
        END IF;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO system_audit_logs (table_name, record_id, action, old_data, changed_by)
        VALUES (TG_TABLE_NAME, record_identifier, 'DELETE', row_to_json(OLD)::jsonb, sys_user);
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Obtener Ventas para Gráfico de Ventas
CREATE OR REPLACE FUNCTION public.get_sales_chart_data(
    p_start_date date, 
    p_end_date date, 
    p_interval text
) RETURNS TABLE(day text, total numeric, cnt bigint) AS $$
BEGIN
  RETURN QUERY
  WITH series AS (
    SELECT generate_series(
      p_start_date::timestamp, 
      p_end_date::timestamp, 
      ('1 ' || p_interval)::interval
    )::date as day
  ),
  sales AS (
    SELECT 
      date_trunc(p_interval, created_at)::date as sales_day,
      SUM(total) as total,
      COUNT(*) as cnt
    FROM pedidos
    WHERE status = 'Entregado' 
      AND created_at >= p_start_date
      AND created_at < p_end_date + interval '1 day'
    GROUP BY 1
  )
  SELECT 
    to_char(s.day, 'YYYY-MM-DD'),
    COALESCE(sl.total, 0),
    COALESCE(sl.cnt, 0)
  FROM series s
  LEFT JOIN sales sl ON s.day = sl.sales_day
  ORDER BY s.day;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger: Sincronizar Stock desde el historial de movimientos de Kardex
CREATE OR REPLACE FUNCTION public.sync_stock_from_kardex()
RETURNS trigger AS $$
DECLARE
    calc_producto_id BIGINT;
    calc_variante_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        calc_producto_id := OLD.producto_id;
        calc_variante_id := OLD.variante_id;
    ELSE
        calc_producto_id := NEW.producto_id;
        calc_variante_id := NEW.variante_id;
    END IF;

    IF calc_variante_id IS NOT NULL THEN
        UPDATE public.producto_variantes 
        SET stock = (
            SELECT COALESCE(SUM(cantidad), 0)
            FROM public.inventario_movimientos
            WHERE variante_id = calc_variante_id
        )
        WHERE id = calc_variante_id;
    ELSE
        UPDATE public.productos
        SET stock = (
            SELECT COALESCE(SUM(cantidad), 0)
            FROM public.inventario_movimientos
            WHERE producto_id = calc_producto_id AND variante_id IS NULL
        )
        WHERE id = calc_producto_id;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Calcular costo promedio ponderado de stock
CREATE OR REPLACE FUNCTION public.get_costo_promedio(p_producto_id bigint, p_variante_id bigint)
RETURNS numeric AS $$
DECLARE
    v_total_cantidad INTEGER := 0;
    v_total_valor NUMERIC(15,2) := 0.00;
    v_mov RECORD;
BEGIN
    FOR v_mov IN 
        SELECT cantidad, costo_unitario, tipo_movimiento
        FROM public.inventario_movimientos
        WHERE producto_id = p_producto_id 
          AND (variante_id = p_variante_id OR (variante_id IS NULL AND p_variante_id IS NULL))
        ORDER BY created_at ASC, id ASC
    LOOP
        IF v_mov.cantidad > 0 THEN
            v_total_valor := v_total_valor + (v_mov.cantidad * v_mov.costo_unitario);
            v_total_cantidad := v_total_cantidad + v_mov.cantidad;
        ELSE
            IF v_total_cantidad > 0 THEN
                v_total_valor := v_total_valor + (v_mov.cantidad * (v_total_valor / v_total_cantidad));
            END IF;
            v_total_cantidad := v_total_cantidad + v_mov.cantidad;
        END IF;
    END LOOP;
    
    IF v_total_cantidad <= 0 THEN
        RETURN 0.00;
    END IF;
    
    RETURN ROUND(v_total_valor / v_total_cantidad, 2);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Descuento Atómico de Stock de Pedidos vía Movimiento Kardex
CREATE OR REPLACE FUNCTION public.admin_procesar_descuento_stock(
  p_pedido_id BIGINT,
  p_revertir BOOLEAN DEFAULT false
) RETURNS BOOLEAN AS $$
DECLARE
  v_item RECORD;
  v_mov_tipo TEXT;
  v_multiplicador INTEGER;
  v_costo_unitario NUMERIC(10,2);
BEGIN
  IF NOT p_revertir THEN
    v_mov_tipo := 'SALIDA_VENTA';
    v_multiplicador := -1;
  ELSE
    v_mov_tipo := 'DEVOLUCION'; 
    v_multiplicador := 1;
  END IF;

  FOR v_item IN 
    SELECT producto_id, producto_variante_id, cantidad 
    FROM pedido_items 
    WHERE pedido_id = p_pedido_id
  LOOP
    v_costo_unitario := public.get_costo_promedio(v_item.producto_id, v_item.producto_variante_id);

    INSERT INTO public.inventario_movimientos (
        producto_id, 
        variante_id, 
        almacen_id, 
        tipo_movimiento, 
        cantidad, 
        costo_unitario,
        referencia,
        notas
    ) VALUES (
        v_item.producto_id,
        v_item.producto_variante_id,
        1,
        v_mov_tipo,
        v_item.cantidad * v_multiplicador,
        v_costo_unitario,
        'PEDIDO-' || p_pedido_id::text,
        CASE WHEN p_revertir THEN 'Reversión de stock de pedido' ELSE 'Descuento de stock por venta' END
    );
  END LOOP;

  UPDATE pedidos 
  SET stock_descontado = NOT p_revertir 
  WHERE id = p_pedido_id;

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Obtener Productos Más Vendidos
CREATE OR REPLACE FUNCTION public.get_top_products(exclude_id bigint, limit_count integer)
RETURNS SETOF public.productos AS $$
BEGIN
  RETURN QUERY
  SELECT p.*
  FROM public.productos p
  LEFT JOIN public.pedido_items pi ON pi.producto_id = p.id
  LEFT JOIN public.pedidos pe ON pe.id = pi.pedido_id
  WHERE (exclude_id IS NULL OR p.id <> exclude_id)
    AND COALESCE(p.stock, 0) > 0
  GROUP BY p.id
  ORDER BY COALESCE(SUM(pi.cantidad), 0) DESC, p.created_at DESC
  LIMIT limit_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==========================================
-- 📂 5. Asignación de Triggers a Tablas
-- ==========================================

-- Trigger: Cupón automático en inserciones de pedidos
CREATE TRIGGER before_insert_apply_coupon
BEFORE INSERT ON public.pedidos
FOR EACH ROW EXECUTE FUNCTION public.apply_coupon_to_pedido();

-- Triggers: Auditoría de Cambios
CREATE TRIGGER audit_productos
AFTER INSERT OR UPDATE OR DELETE ON public.productos
FOR EACH ROW EXECUTE FUNCTION public.log_changes_trigger();

CREATE TRIGGER audit_categorias
AFTER INSERT OR UPDATE OR DELETE ON public.categorias
FOR EACH ROW EXECUTE FUNCTION public.log_changes_trigger();

CREATE TRIGGER audit_cupones
AFTER INSERT OR UPDATE OR DELETE ON public.cupones
FOR EACH ROW EXECUTE FUNCTION public.log_changes_trigger();

CREATE TRIGGER audit_announcement_bar
AFTER INSERT OR UPDATE OR DELETE ON public.announcement_bar
FOR EACH ROW EXECUTE FUNCTION public.log_changes_trigger();

CREATE TRIGGER audit_home_banners
AFTER INSERT OR UPDATE OR DELETE ON public.home_banners
FOR EACH ROW EXECUTE FUNCTION public.log_changes_trigger();

-- Trigger: Slugify en Productos creados
CREATE TRIGGER on_product_created_set_slug
BEFORE INSERT ON public.productos
FOR EACH ROW EXECUTE FUNCTION public.handle_new_product_slug();

-- Trigger: Sincronizar Stock Automático por Kardex
CREATE TRIGGER trigger_sync_stock
AFTER INSERT OR UPDATE OR DELETE ON public.inventario_movimientos
FOR EACH ROW EXECUTE FUNCTION public.sync_stock_from_kardex();

-- ==========================================
-- 📂 6. Políticas de Seguridad (RLS)
-- ==========================================

-- Habilitar RLS en todas las tablas
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidencias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cupones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.producto_variantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.producto_especificaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.home_banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcement_bar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido_pagos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido_notas ENABLE ROW LEVEL SECURITY;

-- 🛡️ Políticas para: pedido_notas
CREATE POLICY "Permitir borrado admin" ON public.pedido_notas FOR DELETE USING (public.is_admin());
CREATE POLICY "Permitir lectura staff" ON public.pedido_notas FOR SELECT TO authenticated USING (public.can_access_pedido(pedido_id));
CREATE POLICY "Permitir escritura staff" ON public.pedido_notas FOR INSERT TO authenticated WITH CHECK (public.can_access_pedido(pedido_id));
ALTER TABLE public.almacenes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventario_movimientos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_pixels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.newsletter_subscriptions ENABLE ROW LEVEL SECURITY;

-- 🛡️ Políticas para: marketing_pixels
CREATE POLICY "Admins gestionan píxeles" ON public.marketing_pixels FOR ALL USING (public.check_user_role(ARRAY['admin'::text]));
CREATE POLICY "Permitir lectura de píxeles" ON public.marketing_pixels FOR SELECT USING (true);

-- 🛡️ Políticas para: newsletter_subscriptions
CREATE POLICY "Admin read subscriptions" ON public.newsletter_subscriptions FOR SELECT USING (public.is_admin());
CREATE POLICY "Anon/Service insert subscriptions" ON public.newsletter_subscriptions FOR INSERT WITH CHECK (true);

-- 🛡️ Políticas para: categorias
CREATE POLICY categorias_select_anon ON public.categorias FOR SELECT TO anon USING (true);
CREATE POLICY categorias_select_authenticated ON public.categorias FOR SELECT TO authenticated USING (true);
CREATE POLICY categorias_admin_manage ON public.categorias FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY categorias_admin_update ON public.categorias FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY categorias_admin_delete ON public.categorias FOR DELETE TO authenticated USING (public.is_admin());
CREATE POLICY "Public read categories" ON public.categorias FOR SELECT USING (true);
CREATE POLICY "Admin manage categories" ON public.categorias FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- 🛡️ Políticas para: productos
CREATE POLICY productos_select ON public.productos FOR SELECT USING (true);
CREATE POLICY "Public read products" ON public.productos FOR SELECT USING (true);
CREATE POLICY "Admins create products" ON public.productos FOR INSERT WITH CHECK (public.check_user_role(ARRAY['admin'::text]));
CREATE POLICY "Admins delete products" ON public.productos FOR DELETE USING (public.check_user_role(ARRAY['admin'::text]));
CREATE POLICY productos_update ON public.productos FOR UPDATE USING (
    (public.is_admin() OR EXISTS (
        SELECT 1 FROM public.pedido_items pi
        JOIN public.pedidos p ON p.id = pi.pedido_id
        WHERE pi.producto_id = productos.id AND p.asignado_a = auth.uid() AND COALESCE(p.stock_descontado, false) = false
    ))
) WITH CHECK (
    (public.is_admin() OR EXISTS (
        SELECT 1 FROM public.pedido_items pi
        JOIN public.pedidos p ON p.id = pi.pedido_id
        WHERE pi.producto_id = productos.id AND p.asignado_a = auth.uid() AND COALESCE(p.stock_descontado, false) = false
    ))
);

-- 🛡️ Políticas para: clientes
CREATE POLICY "Staff read all clients" ON public.clientes FOR SELECT USING (public.check_user_role(ARRAY['admin'::text, 'worker'::text]));
CREATE POLICY "Admins update clients" ON public.clientes FOR UPDATE USING (public.check_user_role(ARRAY['admin'::text]));
CREATE POLICY "Staff manage clients" ON public.clientes FOR UPDATE USING (public.is_admin() OR public.is_staff());
CREATE POLICY "Staff delete clients" ON public.clientes FOR DELETE USING (public.is_admin());
CREATE POLICY "Public creates clients" ON public.clientes FOR INSERT WITH CHECK ((nombre IS NOT NULL AND length(trim(nombre)) > 0 AND telefono IS NOT NULL AND length(trim(telefono)) > 0));

-- 🛡️ Políticas para: pedidos
CREATE POLICY "Public puede crear pedidos" ON public.pedidos FOR INSERT WITH CHECK ((total IS NOT NULL AND total >= 0::numeric AND COALESCE(status, 'Pendiente'::text) = 'Pendiente'::text));
CREATE POLICY "Public puede leer su propio pedido por charge_id" ON public.pedidos FOR SELECT TO anon USING (culqi_charge_id IS NOT NULL);
CREATE POLICY "Admins ven todos, Workers ven asignados" ON public.pedidos FOR SELECT TO authenticated USING ((public.is_admin() OR (public.is_staff() AND asignado_a = auth.uid())));
CREATE POLICY "Admins y Workers actualizan pedidos" ON public.pedidos FOR UPDATE USING (public.check_user_role(ARRAY['admin'::text, 'worker'::text]));

-- 🛡️ Políticas para: pedido_items
CREATE POLICY "Public puede crear pedido_items" ON public.pedido_items FOR INSERT WITH CHECK ((pedido_id IS NOT NULL AND cantidad IS NOT NULL AND cantidad > 0));
CREATE POLICY "Public puede leer items de pedidos con charge_id" ON public.pedido_items FOR SELECT TO anon USING (EXISTS (SELECT 1 FROM public.pedidos p WHERE p.id = pedido_items.pedido_id AND p.culqi_charge_id IS NOT NULL));
CREATE POLICY "Staff puede leer pedido_items" ON public.pedido_items FOR SELECT USING (public.can_access_pedido(pedido_id));

-- 🛡️ Políticas para: producto_variantes
CREATE POLICY "Public read active variants" ON public.producto_variantes FOR SELECT USING (activo = true);
CREATE POLICY "producto_variantes_select" ON public.producto_variantes FOR SELECT USING ((activo = true OR public.check_user_role(ARRAY['admin'::text, 'worker'::text])));
CREATE POLICY "Admin puede crear producto_variantes" ON public.producto_variantes FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admin puede eliminar producto_variantes" ON public.producto_variantes FOR DELETE USING (public.is_admin());
CREATE POLICY "producto_variantes_update" ON public.producto_variantes FOR UPDATE USING (
    (public.is_admin() OR EXISTS (
        SELECT 1 FROM public.pedido_items pi
        JOIN public.pedidos p ON p.id = pi.pedido_id
        WHERE pi.producto_variante_id = producto_variantes.id AND p.asignado_a = auth.uid() AND COALESCE(p.stock_descontado, false) = false
    ))
) WITH CHECK (
    (public.is_admin() OR EXISTS (
        SELECT 1 FROM public.pedido_items pi
        JOIN public.pedidos p ON p.id = pi.pedido_id
        WHERE pi.producto_variante_id = producto_variantes.id AND p.asignado_a = auth.uid() AND COALESCE(p.stock_descontado, false) = false
    ))
);

-- 🛡️ Políticas para: producto_especificaciones
CREATE POLICY "producto_especificaciones_select" ON public.producto_especificaciones FOR SELECT USING (true);
CREATE POLICY "Admin puede crear producto_especificaciones" ON public.producto_especificaciones FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admin puede actualizar producto_especificaciones" ON public.producto_especificaciones FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admin puede eliminar producto_especificaciones" ON public.producto_especificaciones FOR DELETE USING (public.is_admin());

-- 🛡️ Políticas para: product_reviews
CREATE POLICY "product_reviews_select" ON public.product_reviews FOR SELECT USING ((approved = true OR public.check_user_role(ARRAY['admin'::text, 'worker'::text])));
CREATE POLICY "product_reviews_write_admin" ON public.product_reviews FOR UPDATE USING (public.check_user_role(ARRAY['admin'::text]));

-- 🛡️ Políticas para: product_questions
CREATE POLICY "product_questions_select" ON public.product_questions FOR SELECT USING ((published = true OR public.check_user_role(ARRAY['admin'::text, 'worker'::text])));
CREATE POLICY "product_questions_write_admin" ON public.product_questions FOR UPDATE USING (public.check_user_role(ARRAY['admin'::text, 'worker'::text]));

-- 🛡️ Políticas para: product_answers
CREATE POLICY "product_answers_select" ON public.product_answers FOR SELECT USING ((public.check_user_role(ARRAY['admin'::text, 'worker'::text]) OR (published = true AND EXISTS (SELECT 1 FROM public.product_questions q WHERE q.id = product_answers.question_id AND q.published = true))));
CREATE POLICY "product_answers_write_admin" ON public.product_answers FOR INSERT WITH CHECK (public.check_user_role(ARRAY['admin'::text, 'worker'::text]));

-- 🛡️ Políticas para: announcement_bar
CREATE POLICY "announcement_bar_read" ON public.announcement_bar FOR SELECT USING (true);
CREATE POLICY "announcement_bar_insert" ON public.announcement_bar FOR INSERT WITH CHECK (public.check_user_role(ARRAY['admin'::text]));
CREATE POLICY "announcement_bar_update" ON public.announcement_bar FOR UPDATE USING (public.check_user_role(ARRAY['admin'::text])) WITH CHECK (public.check_user_role(ARRAY['admin'::text]));
CREATE POLICY "announcement_bar_delete" ON public.announcement_bar FOR DELETE USING (public.check_user_role(ARRAY['admin'::text]));

-- 🛡️ Políticas para: home_banners
CREATE POLICY "home_banners_read" ON public.home_banners FOR SELECT USING (true);
CREATE POLICY "home_banners_insert" ON public.home_banners FOR INSERT WITH CHECK (public.check_user_role(ARRAY['admin'::text]));
CREATE POLICY "home_banners_update" ON public.home_banners FOR UPDATE USING (public.check_user_role(ARRAY['admin'::text]));
CREATE POLICY "home_banners_delete" ON public.home_banners FOR DELETE USING (public.check_user_role(ARRAY['admin'::text]));

-- 🛡️ Políticas para: social_links
CREATE POLICY "social_links_select_anon" ON public.social_links FOR SELECT TO anon USING (true);
CREATE POLICY "social_links_select_authenticated" ON public.social_links FOR SELECT TO authenticated USING (true);
CREATE POLICY "social_links_admin_insert" ON public.social_links FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY "social_links_admin_update" ON public.social_links FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "social_links_admin_delete" ON public.social_links FOR DELETE TO authenticated USING (public.is_admin());
CREATE POLICY "Public read social links" ON public.social_links FOR SELECT USING (true);
CREATE POLICY "Admin manage social links" ON public.social_links FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- 🛡️ Políticas para: usuarios
CREATE POLICY "usuarios_select" ON public.usuarios FOR SELECT USING ((id = auth.uid() OR public.check_user_role(ARRAY['admin'::text, 'worker'::text])));
CREATE POLICY "Admins actualizan roles" ON public.usuarios FOR UPDATE USING (public.check_user_role(ARRAY['admin'::text]));

-- 🛡️ Políticas para: pedido_logs
CREATE POLICY "Enable read access for authenticated users" ON public.pedido_logs FOR SELECT TO authenticated USING (true);
CREATE POLICY "Staff read logs" ON public.pedido_logs FOR SELECT USING (public.is_staff());
CREATE POLICY "Staff create logs" ON public.pedido_logs FOR INSERT WITH CHECK (public.is_staff());
CREATE POLICY "Staff puede insertar pedido_logs" ON public.pedido_logs FOR INSERT WITH CHECK (public.check_user_role(ARRAY['admin'::text, 'worker'::text]));

-- 🛡️ Políticas para: system_audit_logs
CREATE POLICY "audit_logs_select" ON public.system_audit_logs FOR SELECT USING (public.is_admin());
CREATE POLICY "Admins read audit logs" ON public.system_audit_logs FOR SELECT USING (public.is_admin());

-- 🛡️ Políticas para: pedido_pagos
CREATE POLICY "Solo admins pueden eliminar pagos" ON public.pedido_pagos FOR DELETE USING (public.is_admin());
CREATE POLICY "Admins y workers pueden ver pagos" ON public.pedido_pagos FOR SELECT TO authenticated USING (public.can_access_pedido(pedido_id));
CREATE POLICY "Admins y workers pueden insertar pagos" ON public.pedido_pagos FOR INSERT TO authenticated WITH CHECK (public.can_access_pedido(pedido_id));

-- 🛡️ Políticas para: pedido_notas
CREATE POLICY "Permitir borrado admin" ON public.pedido_notas FOR DELETE USING (public.is_admin());
CREATE POLICY "Permitir lectura staff" ON public.pedido_notas FOR SELECT TO authenticated USING (public.can_access_pedido(pedido_id));
CREATE POLICY "Permitir escritura staff" ON public.pedido_notas FOR INSERT TO authenticated WITH CHECK (public.can_access_pedido(pedido_id));

-- 🛡️ Políticas para: libro_reclamaciones
CREATE POLICY "Enable read for service role only" ON public.libro_reclamaciones FOR SELECT TO service_role USING (true);
CREATE POLICY "Enable insert for anon users" ON public.libro_reclamaciones FOR INSERT WITH CHECK (
    (nombres IS NOT NULL AND length(trim(nombres)) > 0 AND
     apellidos IS NOT NULL AND length(trim(apellidos)) > 0 AND
     email IS NOT NULL AND email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text AND
     detalle_reclamo IS NOT NULL AND length(trim(detalle_reclamo)) > 0)
);

-- 🛡️ Políticas para: cupones
CREATE POLICY "Admin manage cupones" ON public.cupones FOR ALL USING (public.is_admin());
CREATE POLICY "cupones_select" ON public.cupones FOR SELECT USING ((public.check_user_role(ARRAY['admin'::text]) OR (activo = true AND (starts_at IS NULL OR starts_at <= now()) AND (expires_at IS NULL OR expires_at >= now()) AND (max_usos IS NULL OR usos < max_usos))));
CREATE POLICY "cupones_insert" ON public.cupones FOR INSERT WITH CHECK (public.check_user_role(ARRAY['admin'::text]));
CREATE POLICY "cupones_update" ON public.cupones FOR UPDATE USING (public.check_user_role(ARRAY['admin'::text])) WITH CHECK (public.check_user_role(ARRAY['admin'::text]));
CREATE POLICY "cupones_delete" ON public.cupones FOR DELETE USING (public.check_user_role(ARRAY['admin'::text]));

-- 🛡️ Políticas para: incidencias
CREATE POLICY "incidencias_select" ON public.incidencias FOR SELECT USING (public.check_user_role(ARRAY['admin'::text, 'worker'::text]));
CREATE POLICY "incidencias_insert" ON public.incidencias FOR INSERT WITH CHECK ((public.check_user_role(ARRAY['admin'::text, 'worker'::text]) AND public.can_access_pedido(pedido_id)));
CREATE POLICY "incidencias_update" ON public.incidencias FOR UPDATE USING (public.check_user_role(ARRAY['admin'::text, 'worker'::text])) WITH CHECK (public.check_user_role(ARRAY['admin'::text, 'worker'::text]));
CREATE POLICY "incidencias_delete" ON public.incidencias FOR DELETE USING (public.check_user_role(ARRAY['admin'::text]));

-- =====================================================================
-- 🛡️ Fin de la Consolidación del Esquema Maestro
-- =====================================================================
