create table if not exists pedido_logs (
  id bigint generated by default as identity primary key,
  pedido_id bigint references pedidos(id) on delete cascade not null,
  usuario_nombre text, 
  accion text not null, 
  detalles text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table pedido_logs enable row level security;

create policy "Enable read access for authenticated users" 
on pedido_logs for select 
to authenticated 
using (true);

create policy "Enable insert access for authenticated users" 
on pedido_logs for insert 
to authenticated 
with check (true);
