var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/notify-admin/route.js")
R.c("server/chunks/node_modules_next_916f56a7._.js")
R.c("server/chunks/node_modules_mime-db_f53cdd2e._.js")
R.c("server/chunks/node_modules_axios_dist_node_axios_cjs_ef84af05._.js")
R.c("server/chunks/node_modules_twilio_lib_rest_api_b28c2939._.js")
R.c("server/chunks/node_modules_twilio_lib_rest_chat_3cab13ac._.js")
R.c("server/chunks/node_modules_twilio_lib_rest_conversations_ffec4adb._.js")
R.c("server/chunks/node_modules_twilio_lib_rest_flexApi_20919ac5._.js")
R.c("server/chunks/node_modules_twilio_lib_rest_ipMessaging_c55a9bbd._.js")
R.c("server/chunks/node_modules_twilio_lib_rest_messaging_00dae82e._.js")
R.c("server/chunks/node_modules_twilio_lib_rest_numbers_44f9a22d._.js")
R.c("server/chunks/node_modules_twilio_lib_rest_studio_45f7f167._.js")
R.c("server/chunks/node_modules_twilio_lib_rest_taskrouter_84f08b9a._.js")
R.c("server/chunks/node_modules_twilio_lib_rest_trusthub_ddd0de17._.js")
R.c("server/chunks/node_modules_twilio_lib_rest_verify_272ffc87._.js")
R.c("server/chunks/node_modules_twilio_lib_rest_video_f0e580d7._.js")
R.c("server/chunks/node_modules_twilio_lib_rest_7c869895._.js")
R.c("server/chunks/node_modules_twilio_lib_8c2b704c._.js")
R.c("server/chunks/node_modules_twilio_package_json_fd841883._.js")
R.c("server/chunks/node_modules_xmlbuilder_lib_bfb18792._.js")
R.c("server/chunks/node_modules_2a1b5b58._.js")
R.c("server/chunks/[root-of-the-server]__a2bb2c6c._.js")
R.c("server/chunks/_next-internal_server_app_api_notify-admin_route_actions_1ff4f6a9.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/notify-admin/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/notify-admin/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
