var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/node_modules_next_dist_93bb6814._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ae375ec._.js")
R.c("server/chunks/ssr/node_modules_91333dfc._.js")
R.c("server/chunks/ssr/[externals]__e8a2741f._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/[externals]_next_dist_compiled_@vercel_og_index_node_9938dfd7.js")
R.c("server/chunks/ssr/_de1aab74._.js")
R.c("server/chunks/ssr/app_e8f21c77._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f9d2bb6c._.js")
R.c("server/chunks/ssr/node_modules_96d29d66._.js")
R.c("server/chunks/ssr/_ddb40ced._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_554ec2bf.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/_not-found/page { METADATA_0 => \"[project]/app/favicon.ico.mjs { IMAGE => \\\"[project]/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", METADATA_1 => \"[project]/app/twitter-image--metadata.js [app-rsc] (ecmascript, Next.js Server Component)\", METADATA_2 => \"[project]/app/opengraph-image--metadata.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/_not-found/page { METADATA_0 => \"[project]/app/favicon.ico.mjs { IMAGE => \\\"[project]/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", METADATA_1 => \"[project]/app/twitter-image--metadata.js [app-rsc] (ecmascript, Next.js Server Component)\", METADATA_2 => \"[project]/app/opengraph-image--metadata.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
