module.exports = [
"[project]/app/favicon.ico.mjs { IMAGE => \"[project]/app/favicon.ico (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/favicon.ico.mjs { IMAGE => \"[project]/app/favicon.ico (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript)"));
}),
"[project]/app/twitter-image--metadata.js [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/twitter-image--metadata.js [app-rsc] (ecmascript)"));
}),
"[project]/app/opengraph-image--metadata.js [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/opengraph-image--metadata.js [app-rsc] (ecmascript)"));
}),
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/app/productos/[id]/producto-detalle-client.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/app/productos/[id]/producto-detalle-client.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/app/productos/[id]/producto-detalle-client.tsx <module evaluation>", "default");
}),
"[project]/app/productos/[id]/producto-detalle-client.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/app/productos/[id]/producto-detalle-client.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/app/productos/[id]/producto-detalle-client.tsx", "default");
}),
"[project]/app/productos/[id]/producto-detalle-client.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$app$2f$productos$2f5b$id$5d2f$producto$2d$detalle$2d$client$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/app/productos/[id]/producto-detalle-client.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$app$2f$productos$2f5b$id$5d2f$producto$2d$detalle$2d$client$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/app/productos/[id]/producto-detalle-client.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$app$2f$productos$2f5b$id$5d2f$producto$2d$detalle$2d$client$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/features/products/services/products.server.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "fetchProductForMeta",
    ()=>fetchProductForMeta,
    "getHomePageData",
    ()=>getHomePageData
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$supabase$2f$supabase$2d$js$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/node_modules/@supabase/supabase-js/dist/index.mjs [app-rsc] (ecmascript) <locals>");
;
function createAnonServerClient() {
    const supabaseUrl = ("TURBOPACK compile-time value", "https://pvgghvcqoxhcozlyagwz.supabase.co");
    const supabaseAnonKey = ("TURBOPACK compile-time value", "sb_publishable_fa2tkyQJswbluGvWIwXTtw_YYevu4NL");
    if ("TURBOPACK compile-time falsy", 0) //TURBOPACK unreachable
    ;
    return (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$supabase$2f$supabase$2d$js$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__["createClient"])(supabaseUrl, supabaseAnonKey, {
        auth: {
            persistSession: false
        }
    });
}
async function fetchProductForMeta(id) {
    const supabase = createAnonServerClient();
    if (!supabase) return null;
    const { data, error } = await supabase.from("productos").select("id, nombre, descripcion, imagen_url, imagenes").eq("id", id).maybeSingle();
    if (error) return null;
    return data;
}
async function getHomePageData(opts) {
    const supabase = createAnonServerClient();
    if (!supabase) {
        return {
            categories: [],
            featuredProduct: null,
            products: [],
            bestSellers: [],
            offers: [],
            productsError: null
        };
    }
    const { data: categories } = await supabase.from("categorias").select("*").order("nombre", {
        ascending: true
    });
    const selectedCategorySlug = String(opts.selectedCategorySlug || "").trim();
    const selectedCategory = categories?.find((c)=>c.slug === selectedCategorySlug);
    const { data: featuredProduct } = await supabase.from("productos").select("*").ilike("nombre", opts.featuredQuery).order("created_at", {
        ascending: false
    }).limit(1).maybeSingle();
    let productsQuery = supabase.from("productos").select("*").order("created_at", {
        ascending: false
    });
    productsQuery = productsQuery.limit(opts.productsLimit);
    if (selectedCategory?.id) {
        const catId = selectedCategory.id;
        const allCats = categories || [];
        const childIds = allCats.filter((c)=>c.parent_id === catId).map((c)=>c.id);
        const ids = [
            catId,
            ...childIds
        ];
        productsQuery = productsQuery.in("categoria_id", ids);
    }
    const { data: products, error: productsError } = await productsQuery;
    let bestSellers = [];
    let offers = [];
    try {
        const { data: soldItems, error: soldItemsError } = await supabase.from("pedido_items").select(`
        cantidad,
        productos (*),
        pedidos (status)
      `).limit(1000);
        if (!soldItemsError && soldItems && soldItems.length > 0) {
            const soldByProductId = new Map();
            for (const row of soldItems){
                const status = row.pedidos?.status;
                if (status && [
                    "Fallido",
                    "Devuelto"
                ].includes(status)) continue;
                const product = row.productos;
                if (!product) continue;
                const productId = product.id;
                const qty = Number(row.cantidad) || 0;
                if (qty <= 0) continue;
                const current = soldByProductId.get(productId);
                if (current) {
                    current.sold += qty;
                } else {
                    soldByProductId.set(productId, {
                        product,
                        sold: qty
                    });
                }
            }
            bestSellers = Array.from(soldByProductId.values()).sort((a, b)=>b.sold - a.sold).slice(0, 10).map((x)=>x.product);
        }
    } catch (err) {
        bestSellers = [];
    }
    try {
        const { data: offersRaw, error: offersError } = await supabase.from("productos").select("*").not("precio_antes", "is", null).limit(60);
        if (!offersError && offersRaw && offersRaw.length > 0) {
            offers = offersRaw.filter((p)=>{
                const before = Number(p?.precio_antes ?? 0);
                const current = Number(p?.precio ?? 0);
                return Number.isFinite(before) && Number.isFinite(current) && before > current && current > 0;
            }).sort((a, b)=>{
                const beforeA = Number(a?.precio_antes ?? 0);
                const currentA = Number(a?.precio ?? 0);
                const beforeB = Number(b?.precio_antes ?? 0);
                const currentB = Number(b?.precio ?? 0);
                const discA = beforeA > 0 ? (beforeA - currentA) / beforeA : 0;
                const discB = beforeB > 0 ? (beforeB - currentB) / beforeB : 0;
                return discB - discA;
            }).slice(0, 6);
        }
    } catch (err) {
        offers = [];
    }
    const visibleCategories = (categories || []).filter((c)=>!c.parent_id);
    return {
        categories: visibleCategories,
        featuredProduct: featuredProduct || null,
        products: products || [],
        bestSellers,
        offers,
        productsError
    };
}
}),
"[project]/app/productos/[id]/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>ProductoDetallePage,
    "generateMetadata",
    ()=>generateMetadata
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$app$2f$productos$2f5b$id$5d2f$producto$2d$detalle$2d$client$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/app/productos/[id]/producto-detalle-client.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$features$2f$products$2f$services$2f$products$2e$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/features/products/services/products.server.ts [app-rsc] (ecmascript)");
;
;
;
function parseProductId(raw) {
    const direct = Number(raw);
    if (Number.isFinite(direct) && direct > 0) return direct;
    const match = String(raw).match(/(\d+)(?:\D*)$/);
    if (match && match[1]) return Number(match[1]);
    return 0;
}
function buildDescription(p) {
    const raw = String(p?.descripcion || "").trim();
    const safe = raw.replace(/\s+/g, " ").slice(0, 160);
    if (safe) return safe;
    return "Compra online con entrega rápida y compra segura.";
}
async function generateMetadata({ params }) {
    const resolvedParams = await params;
    const id = parseProductId(resolvedParams.id);
    if (!id) {
        return {
            title: "Producto",
            description: "Detalle de producto"
        };
    }
    const product = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$features$2f$products$2f$services$2f$products$2e$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["fetchProductForMeta"])(id);
    if (!product) {
        return {
            title: "Producto",
            description: "Detalle de producto"
        };
    }
    const title = String(product.nombre || "Producto");
    const description = buildDescription(product);
    const imgs = Array.isArray(product.imagenes) ? product.imagenes.filter(Boolean) : [];
    const primaryImage = imgs[0] || String(product.imagen_url || "");
    return {
        title,
        description,
        openGraph: {
            title,
            description,
            images: primaryImage ? [
                {
                    url: primaryImage
                }
            ] : []
        },
        twitter: {
            card: "summary_large_image",
            title,
            description,
            images: primaryImage ? [
                primaryImage
            ] : []
        }
    };
}
function ProductoDetallePage() {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$app$2f$productos$2f5b$id$5d2f$producto$2d$detalle$2d$client$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {}, void 0, false, {
        fileName: "[project]/app/productos/[id]/page.tsx",
        lineNumber: 65,
        columnNumber: 12
    }, this);
}
}),
"[project]/app/productos/[id]/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/productos/[id]/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__bcc10880._.js.map