// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/announcement-bar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/announcement-bar">> = Specific
  const handler = {} as typeof import("../../../app/admin/announcement-bar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/banners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/banners">> = Specific
  const handler = {} as typeof import("../../../app/admin/banners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clientes">> = Specific
  const handler = {} as typeof import("../../../app/admin/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/cupones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cupones">> = Specific
  const handler = {} as typeof import("../../../app/admin/cupones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/pedidos-en-proceso/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard/pedidos-en-proceso">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/pedidos-en-proceso/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/pedidos-pendientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard/pedidos-pendientes">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/pedidos-pendientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/stock-bajo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard/stock-bajo">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/stock-bajo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/ventas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard/ventas">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/ventas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/incidencias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/incidencias">> = Specific
  const handler = {} as typeof import("../../../app/admin/incidencias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/pedidos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pedidos/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/pedidos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/pedidos/[id]/ticket/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pedidos/[id]/ticket">> = Specific
  const handler = {} as typeof import("../../../app/admin/pedidos/[id]/ticket/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/pedidos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pedidos">> = Specific
  const handler = {} as typeof import("../../../app/admin/pedidos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/preguntas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/preguntas">> = Specific
  const handler = {} as typeof import("../../../app/admin/preguntas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/productos/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/productos/[id]/editar">> = Specific
  const handler = {} as typeof import("../../../app/admin/productos/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/productos/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/productos/nuevo">> = Specific
  const handler = {} as typeof import("../../../app/admin/productos/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/productos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/productos">> = Specific
  const handler = {} as typeof import("../../../app/admin/productos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/resenas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/resenas">> = Specific
  const handler = {} as typeof import("../../../app/admin/resenas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/usuarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/usuarios">> = Specific
  const handler = {} as typeof import("../../../app/admin/usuarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../../app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contacto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacto">> = Specific
  const handler = {} as typeof import("../../../app/contacto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/envios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/envios">> = Specific
  const handler = {} as typeof import("../../../app/envios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/nosotros/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nosotros">> = Specific
  const handler = {} as typeof import("../../../app/nosotros/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/open-wa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/open-wa">> = Specific
  const handler = {} as typeof import("../../../app/open-wa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacidad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacidad">> = Specific
  const handler = {} as typeof import("../../../app/privacidad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/productos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/productos/[id]">> = Specific
  const handler = {} as typeof import("../../../app/productos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/productos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/productos">> = Specific
  const handler = {} as typeof import("../../../app/productos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terminos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terminos">> = Specific
  const handler = {} as typeof import("../../../app/terminos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/announcement-bar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/announcement-bar">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/announcement-bar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/create-worker/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/create-worker">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/create-worker/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/productos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/productos">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/productos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/checkout/whatsapp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout/whatsapp">> = Specific
  const handler = {} as typeof import("../../../app/api/checkout/whatsapp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notify-admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notify-admin">> = Specific
  const handler = {} as typeof import("../../../app/api/notify-admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/questions/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/questions/submit">> = Specific
  const handler = {} as typeof import("../../../app/api/questions/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reviews/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews/submit">> = Specific
  const handler = {} as typeof import("../../../app/api/reviews/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
